name: Run Tests

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Extism and XTP
        run: |
          curl https://raw.githubusercontent.com/extism/js-pdk/main/install.sh | bash -s v1.3.3
          curl https://static.dylibso.com/cli/install.sh | bash

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21'

      - name: Install
        run: |
          npm ci
          npm install -g ejs-lint

      - name: Build
        run: |
          npm run build

      - name: Install Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.13.0
  
      - name: Check Zig Version
        run: zig version
          

      - name: Run test script
        run: |
          cd tests && ./test.sh

      - name: Run Bindgen Test
        run: |
          extism-js --version
          
          sh bindgen-test.sh install
          sh bindgen-test.sh run

